Fix/small UI tweaks
UCL/kapta-mobile pull request #15
Opened 2024-07-23 15:51 UTC by acholyn

addresses #5 
closes #11 & #7

2024-07-23 16:42 UTC, MarcosMoreu reviewed
I haven't installed it with this fix. Just checking if replacing the icons has fixed the problem of wrong size/display in the homescreen & splash logo once installed??

2024-07-23 16:43 UTC, MarcosMoreu approved these changes

2024-07-23 16:43 UTC, MarcosMoreu approved these changes

2024-07-23 20:08 UTC, MarcosMoreu commented on src/styles/main.css
> +        font-size: 108%;
Looks that it doesn't fit in a/some mobile screen. Keep it as 106 with the emojis in the next line (so emojis in between the text lines). Makes sense?

2024-07-23 20:18 UTC, MarcosMoreu commented on src/styles/main.css
> +        font-size: 150%;
I just tested it and with this font doesn't fit to some mobile screen. Let's use 120%.

2024-07-23 21:10 UTC, MarcosMoreu requested changes
Still with this icons the maskable property in the manifest doesn't seem to work properly. The easiest solution is to use the previous icons with some margin. I've tried and it just works.

Replace with the attached 
[resized_images_new_3.zip](https://github.com/user-attachments/files/16354332/resized_images_new_3.zip)

2024-08-21 11:32 UTC, MarcosMoreu approved these changes

2024-08-21 11:53 UTC, acholyn commented
video can be made full screen by clicking the option but the modal should sit just below the "how to" title 
<img width="281" alt="image" src="https://github.com/user-attachments/assets/0bf6b27c-9159-4cef-aa44-63c6772ffac5">

2024-08-21 11:53 UTC, merged